### ISSUE TITLE
Basic auth Rotom Version 

### ISSUE THREAD

**Issue by HTPaddy** [Kneckter/RDMMonitor#26]
I’m using a basic auth dir my rotom dashboard, with that rdmmonitor is unable to connect to /api/status

Maybe a basic auth login could get implemented into the Rotommonitor version ?

**Comment by Kneckter** [comment]
You can pull the latest version and setup the BasicAuth fields. This is only the auth for reverse proxies (NGINX/Apache2) and not the listener endpoints. If it's good with you, will you close the issue?

**Comment by plinytheelder** [comment]
well, this might work if you have auth enabled. but if you don't have auth then the rotom device query fails. so might need to be an if blank, omit `WEBSITE_AUTH`

**Comment by Kneckter** [comment]
I don't have auth enabled and it wasn't failing for me. What was the specific error?

**Comment by plinytheelder** [comment]
I guess it's ok. I actually didn't add it to my config so that caused the error. adding the items with blank variables made it not angry.

**Comment by Kneckter** [comment]
Oh, yeah. That would do it since I didn't have a default value.

**Comment by Kneckter** [comment]
I'm going to close this since it's been working and I added default strings to not trip-up others.
