### ISSUE TITLE
Bug: Rotom version crash and restart

### ISSUE THREAD

**Issue by billbob654** [Kneckter/RDMMonitor#27]
When testing the new Rotom version of this when a device/worker goes offline and it attempts to start a reboot RDMMonitor crashes and restarts

The error that displays says
Uncaught exception {}
Restarting in 1 min

If I run a reboot command manually in a channel it works and sends the command to the listener and restarts the device 

I'm running android with GCv3 don't know if this has anything to do with it

**Comment by Kneckter** [comment]
Did you type that error from memory instead of copy/pasting it? It should be different on the latest version

**Comment by Kneckter** [comment]
You can pull the new update and retry. I was referencing the `name` key when doing auto reopen/restart. It shouldn't come up now

**Comment by billbob654** [comment]
Thanks this fixes the issue I was having and now working with no issues
