### ISSUE TITLE
Restarting Rotoms creates Random Devices

### ISSUE THREAD

**Issue by plinytheelder** [Kneckter/RDMMonitor#31]
Everytime I restart rotom, rotomonitor adds random devices with random characters. Not sure if this is a rotomonitor issue or a rotom API issue.
![image](https://github.com/Kneckter/Rotomonitor/assets/25189524/34303911-c165-43bf-9407-edb9cc2f260a)

**Comment by Kneckter** [comment]
Was there an error captured in the Rotomonitor log? I've tried restarting Rotom while the monitor was poling but I did not see this issue yet.

**Comment by Kneckter** [comment]
References from Lokixx
![image](https://github.com/Kneckter/Rotomonitor/assets/16466177/1dc318ee-75c7-436f-bc11-fc8c1f460aa4)
![image](https://github.com/Kneckter/Rotomonitor/assets/16466177/209ce22c-1f4c-4a4b-b3f4-57da0acc25fd)

**Comment by Kneckter** [comment]
Rotom log from Atsu about this issue
```
rotom  | [2023-12-12T12:05:57.941Z] [INFO] [rotom] Device: New connection from ::ffff:172.25.0.26 url /
rotom  | [2023-12-12T12:05:58.229Z] [INFO] [rotom] ȁ/929: Received id packet origin  - version 0
rotom  | [2023-12-12T12:05:58.229Z] [INFO] [rotom] ȁ: unallocated connections = ȁ
rotom  | [2023-12-12T12:05:59.877Z] [INFO] [rotom] CONTROLLER: Found null connects to workerId ȁ
rotom  | [2023-12-12T12:05:59.877Z] [INFO] [rotom] CONTROLLER: Warning - found ȁ in pool with no record of main device
rotom  | [2023-12-12T12:05:59.877Z] [INFO] [rotom] CONTROLLER: New connection from ::ffff:172.25.0.3 - no Devices available outside cooldown, rejecting
```

**Comment by Kneckter** [comment]
We might be able to ignore these by checking for surrogate characters. I pushed an update with commit 743d524
